#!/usr/bin/env bash

case $BLOCK_BUTTON in
    3) pgrep -x dunst >/dev/null && notify-send "<b>🔋 Battery module:</b>
🔋: discharging
🛑: not charging
♻: stagnant charge
🔌: charging
⚡: charged
❗: battery very low!
- Text color reflects charge left" ;;
esac

declare -a options
options[0]="high"
options[1]="low"
options[2]="critical"
options[3]="charging"

capacity=$(apm -l) || exit

status=${options[$(apm -b)]}

if [ "$capacity" -ge 75 ]; then
    color="#00ff00"
elif [ "$capacity" -ge 50 ]; then
    color="#ffffff"
elif [ "$capacity" -ge 25 ]; then
    color="#ffff00"
else
    color="#ff0000"
    warn="❗"
fi

[ -z $warn ] && warn=" "

[ "$status" = "charging" ] && color="#ffffff"

printf "<span color='%s'>%s%s%s</span>" "$color" "$(echo "$status" | sed -e "s/,//;s/critical/🔋/;s/Not Charging/🛑/;s/charging/🔌/;s/Unknown/♻️/;s/high/⚡/;s/ 0*/ /g;s/ :/ /g")" "$warn" "$(echo "$capacity" | sed -e 's/$/%/')"
