#!/bin/sh

case $BLOCK_BUTTON in
  1) "$TERMINAL" -e neomutt ;;
  3) grep -x dunst > /dev/null && notify-send "<> Mail module:</b>
  - Shows unread mail
  - Shows X if syncing mail
  - Left click opens neomutt
  - Middle click syncs mail" ;;
esac

#echo "$(du -a ~/.mail/*/inbox/new/* 2>/dev/null | sed -n '$=')$(cat ~/.config/mutt/.dl 2>/dev/null)"
echo "$(du -a ~/.mail/*/inbox/new/* 2>/dev/null | sed -n '$=')"

