#!/bin/sh

# credits
# https://linuxconfig.org/polybar-a-better-wm-panel-for-your-linux-system

IP=$(drill +short myip.opendns.com @resolver1.opendns.com | grep 'IN\s*A\s' | awk '{print $5}')

if pgrep -x openvpn > /dev/null; then
    echo VPN: $IP
else
    echo $IP
fi
