#!/bin/sh

bspc monitor -d Oz Hyrule Winterfell Hogwarts Narnia MiddleEarth Earthsea Neverland Wonderland Gotham
#bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config top_padding          16
bspc config bottom_padding          16

bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Zathura state=tiled

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off

#compton --config "$HOME/.config/compton.conf" -b

bspc rule --add scratchpad sticky=on center=on state=floating hidden=on border=on
#st -c scratchpad -e telegram-cli &
#[ "$(ps -x | grep -c 'scratchpad')" -eq "1" ] && st -c scratchpad

bspc rule --add mon sticky=on center=on state=floating hidden=on
#[ "$(ps -x | grep -c 'mon')" -eq "1" ] && st -c mon -e monitor &

