#!/bin/sh
# Sets the background. If given an argument, will set file as background.
[ ! -z "$1" ] && cp "$1" ~/.wallpapers/current && notify-send -i "$HOME/.wallpapers/current" "Wallpaper changed."
#xwallpaper --zoom ~/.config/wall.png
feh --bg-scale ~/.wallpapers/current

