#!/bin/sh

case $BLOCK_BUTTON in
  2) grep -x dunst > /dev/null && notify-send "<b>$(date '+%Y-%m-%d %H:%m')</b>" ;;
esac

color="#e29462"
symbol=""

#printf "<span color='%s'>%s%s</span>" "$color" "$symbol" "$(date '+%H:%M')"
printf "%s %s" "$symbol" "$(date '+%H:%M')"
