#!/bin/sh

case $BLOCK_BUTTON in
  1) notify-send "<b> Memory hogs:</b>
  $(ps axch | head)" ;;
  3) notify-send "<b> Memory module: </b>
  -Shows Memory Used/Total.
  -Click to show memory hogs." ;;
esac

symbol=""
#
#printf "%s  %s" "$symbol" "$(vmstat -h | tail -1 | awk '{print $5 "/" $4}')"
#printf "%s  %s" "$symbol" "$(freecolor -m -o | grep 'Mem' | awk '{printf "%.2f/%.2f", $3/1024, $2/1024}')"
printf "%s %s%%" "$symbol" "$(freecolor -m -o | grep 'Mem' | awk '{printf "%.2f", ($3/$2)*100}')"

#   
