#!/bin/sh

#pkill -RTMIN+5 i3blocks && notify-send "~ Weather forecast updated."
case $BLOCK_BUTTON in
  1) $TERMINAL -e less -S /tmp/weatherreport ;;
  3) pgrep -x dunst >/dev/nul && notify-send "<b> Weather module:</b>
  - Click for wttr.in forecast.
  x: Chance of rain/snow
  y: Daily low
  z: Daily high" ;;
esac

symbol=""

curl -s wttr.in/Santiago?format='%t+%m' >/tmp/weatherreport || exit 1

printf "%s %s" "$symbol" "$(cat /tmp/weatherreport)"
